#pragma once

#define LED_CYCLE_ON 0
#define LED_CYCLE_OFF 1
#define LED_CYCLE_RANDOM 2
#define LED_CYCLE_MOTION 3
#define LED_CYCLE_BLINK 4
//#define LED_CYCLE_ 5
#define LED_CYCLE_ROTATION 6

#define LED_PRESET_OFF 0
#define LED_PRESET_SAFETY 1
#define LED_PRESET_RAINBOW 2
#define LED_PRESET_MIDNIGHT 3
#define LED_PRESET_PRIDE 4
#define LED_PRESET_WHITE 5
